Import gsoap v2.4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Autoconf 2.52 for soapcpp2 2.3.
+# Generated by Autoconf 2.52 for soapcpp2 2.4.
 #
 # Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
 # Free Software Foundation, Inc.
@@ -183,8 +183,8 @@ mandir='${prefix}/man'
 # Identity of this package.
 PACKAGE_NAME='soapcpp2'
 PACKAGE_TARNAME='soapcpp2'
-PACKAGE_VERSION='2.3'
-PACKAGE_STRING='soapcpp2 2.3'
+PACKAGE_VERSION='2.4'
+PACKAGE_STRING='soapcpp2 2.4'
 PACKAGE_BUGREPORT=''
 
 ac_prev=
@@ -609,7 +609,7 @@ if test "$ac_init_help" = "long"; then
   # Omit some internal or obsolete options to make the list less imposing.
   # This message is too long to be a string in the A/UX 3.1 sh.
   cat <<EOF
-\`configure' configures soapcpp2 2.3 to adapt to many kinds of systems.
+\`configure' configures soapcpp2 2.4 to adapt to many kinds of systems.
 
 Usage: $0 [OPTION]... [VAR=VALUE]...
 
@@ -675,7 +675,7 @@ fi
 
 if test -n "$ac_init_help"; then
   case $ac_init_help in
-     short | recursive ) echo "Configuration of soapcpp2 2.3:";;
+     short | recursive ) echo "Configuration of soapcpp2 2.4:";;
    esac
   cat <<\EOF
 
@@ -743,7 +743,7 @@ fi
 test -n "$ac_init_help" && exit 0
 if $ac_init_version; then
   cat <<\EOF
-soapcpp2 configure 2.3
+soapcpp2 configure 2.4
 generated by GNU Autoconf 2.52
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
@@ -758,7 +758,7 @@ cat >&5 <<EOF
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
-It was created by soapcpp2 $as_me 2.3, which was
+It was created by soapcpp2 $as_me 2.4, which was
 generated by GNU Autoconf 2.52.  Invocation command line was
 
   $ $0 $@
@@ -1230,7 +1230,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=soapcpp2
- VERSION=2.3
+ VERSION=2.4
 
 cat >>confdefs.h <<EOF
 #define PACKAGE "$PACKAGE"
@@ -4875,7 +4875,7 @@ else
    YACC_LIB="-ly"
 fi
 
-ac_config_files="$ac_config_files Makefile soapcpp2/Makefile soapcpp2/src/Makefile soapcpp2/samples/Makefile soapcpp2/samples/quote/Makefile soapcpp2/samples/quote2/Makefile soapcpp2/samples/quote3/Makefile soapcpp2/samples/quote4/Makefile soapcpp2/samples/quotex/Makefile soapcpp2/samples/calc/Makefile soapcpp2/samples/factory/Makefile soapcpp2/samples/factorytest/Makefile soapcpp2/samples/dime/Makefile soapcpp2/samples/mybubble/Makefile soapcpp2/samples/localtime/Makefile soapcpp2/samples/listing/Makefile soapcpp2/samples/uddi/Makefile soapcpp2/samples/polytest/Makefile soapcpp2/samples/magic/Makefile soapcpp2/samples/lu/Makefile soapcpp2/samples/ck/Makefile soapcpp2/samples/googleapi/Makefile soapcpp2/samples/varparam/Makefile soapcpp2/samples/ssl/Makefile soapcpp2/samples/router/Makefile soapcpp2/samples/events/Makefile"
+ac_config_files="$ac_config_files Makefile soapcpp2/Makefile soapcpp2/src/Makefile soapcpp2/wsdl/Makefile soapcpp2/samples/Makefile soapcpp2/samples/quote/Makefile soapcpp2/samples/quote2/Makefile soapcpp2/samples/quote3/Makefile soapcpp2/samples/quote4/Makefile soapcpp2/samples/quotex/Makefile soapcpp2/samples/calc/Makefile soapcpp2/samples/factory/Makefile soapcpp2/samples/factorytest/Makefile soapcpp2/samples/dime/Makefile soapcpp2/samples/mybubble/Makefile soapcpp2/samples/localtime/Makefile soapcpp2/samples/listing/Makefile soapcpp2/samples/uddi/Makefile soapcpp2/samples/polytest/Makefile soapcpp2/samples/magic/Makefile soapcpp2/samples/lu/Makefile soapcpp2/samples/ck/Makefile soapcpp2/samples/googleapi/Makefile soapcpp2/samples/varparam/Makefile soapcpp2/samples/ssl/Makefile soapcpp2/samples/router/Makefile soapcpp2/samples/events/Makefile"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -5109,7 +5109,7 @@ EOF
 
 cat >>$CONFIG_STATUS <<EOF
 ac_cs_version="\\
-soapcpp2 config.status 2.3
+soapcpp2 config.status 2.4
 configured by $0, generated by GNU Autoconf 2.52,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
@@ -5192,7 +5192,7 @@ cat >&5 << _ACEOF
 ## Running config.status.  ##
 ## ----------------------- ##
 
-This file was extended by $as_me (soapcpp2 2.3) 2.52, executed with
+This file was extended by $as_me (soapcpp2 2.4) 2.52, executed with
   CONFIG_FILES    = $CONFIG_FILES
   CONFIG_HEADERS  = $CONFIG_HEADERS
   CONFIG_LINKS    = $CONFIG_LINKS
@@ -5220,6 +5220,7 @@ do
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "soapcpp2/Makefile" ) CONFIG_FILES="$CONFIG_FILES soapcpp2/Makefile" ;;
   "soapcpp2/src/Makefile" ) CONFIG_FILES="$CONFIG_FILES soapcpp2/src/Makefile" ;;
+  "soapcpp2/wsdl/Makefile" ) CONFIG_FILES="$CONFIG_FILES soapcpp2/wsdl/Makefile" ;;
   "soapcpp2/samples/Makefile" ) CONFIG_FILES="$CONFIG_FILES soapcpp2/samples/Makefile" ;;
   "soapcpp2/samples/quote/Makefile" ) CONFIG_FILES="$CONFIG_FILES soapcpp2/samples/quote/Makefile" ;;
   "soapcpp2/samples/quote2/Makefile" ) CONFIG_FILES="$CONFIG_FILES soapcpp2/samples/quote2/Makefile" ;;
@@ -5245,7 +5246,7 @@ do
   "soapcpp2/samples/events/Makefile" ) CONFIG_FILES="$CONFIG_FILES soapcpp2/samples/events/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:5248: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:5249: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -5506,7 +5507,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:5509: creating $ac_file" >&5
+    { echo "$as_me:5510: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -5524,7 +5525,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5527: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5528: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5537,7 +5538,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5540: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5541: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5598,7 +5599,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:5601: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:5602: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -5609,7 +5610,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5612: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5613: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5622,7 +5623,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5625: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5626: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5739,7 +5740,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:5742: $ac_file is unchanged" >&5
+      { echo "$as_me:5743: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
