Import gsoap v2.2.2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Autoconf 2.52 for soapcpp2 2.2.1.
+# Generated by Autoconf 2.52 for soapcpp2 2.2.2.
 #
 # Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
 # Free Software Foundation, Inc.
@@ -183,8 +183,8 @@ mandir='${prefix}/man'
 # Identity of this package.
 PACKAGE_NAME='soapcpp2'
 PACKAGE_TARNAME='soapcpp2'
-PACKAGE_VERSION='2.2.1'
-PACKAGE_STRING='soapcpp2 2.2.1'
+PACKAGE_VERSION='2.2.2'
+PACKAGE_STRING='soapcpp2 2.2.2'
 PACKAGE_BUGREPORT=''
 
 ac_prev=
@@ -609,7 +609,7 @@ if test "$ac_init_help" = "long"; then
   # Omit some internal or obsolete options to make the list less imposing.
   # This message is too long to be a string in the A/UX 3.1 sh.
   cat <<EOF
-\`configure' configures soapcpp2 2.2.1 to adapt to many kinds of systems.
+\`configure' configures soapcpp2 2.2.2 to adapt to many kinds of systems.
 
 Usage: $0 [OPTION]... [VAR=VALUE]...
 
@@ -675,7 +675,7 @@ fi
 
 if test -n "$ac_init_help"; then
   case $ac_init_help in
-     short | recursive ) echo "Configuration of soapcpp2 2.2.1:";;
+     short | recursive ) echo "Configuration of soapcpp2 2.2.2:";;
    esac
   cat <<\EOF
 
@@ -743,7 +743,7 @@ fi
 test -n "$ac_init_help" && exit 0
 if $ac_init_version; then
   cat <<\EOF
-soapcpp2 configure 2.2.1
+soapcpp2 configure 2.2.2
 generated by GNU Autoconf 2.52
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
@@ -758,7 +758,7 @@ cat >&5 <<EOF
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
-It was created by soapcpp2 $as_me 2.2.1, which was
+It was created by soapcpp2 $as_me 2.2.2, which was
 generated by GNU Autoconf 2.52.  Invocation command line was
 
   $ $0 $@
@@ -1230,7 +1230,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=soapcpp2
- VERSION=2.2.1
+ VERSION=2.2.2
 
 cat >>confdefs.h <<EOF
 #define PACKAGE "$PACKAGE"
@@ -4755,6 +4755,9 @@ case "${host}" in
         *-*-sysv5*)     platform=UNIXWARE ;;
         *-*-UnixWare*)  platform=UNIXWARE ;;
         *-*-unixware*)  platform=UNIXWARE ;;
+	*-*-sco3.2v5*)  platform=OPENSERVER
+	                SAMPLE_EXTRA_LIBS="-lsocket"
+			;;
         *-*-linux*)     platform=LINUX
 			;;
 	 	*-*-cygwin*)	platform=CYGWIN
@@ -4878,21 +4881,21 @@ fi
 DEFS=-DHAVE_CONFIG_H
 
 if test -z "${AMDEP_TRUE}" && test -z "${AMDEP_FALSE}"; then
-  { { echo "$as_me:4881: error: conditional \"AMDEP\" was never defined.
+  { { echo "$as_me:4884: error: conditional \"AMDEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"AMDEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
 if test -z "${DEBUG_COMPILE_TRUE}" && test -z "${DEBUG_COMPILE_FALSE}"; then
-  { { echo "$as_me:4888: error: conditional \"DEBUG_COMPILE\" was never defined.
+  { { echo "$as_me:4891: error: conditional \"DEBUG_COMPILE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"DEBUG_COMPILE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
 if test -z "${ENABLE_SAMPLES_TRUE}" && test -z "${ENABLE_SAMPLES_FALSE}"; then
-  { { echo "$as_me:4895: error: conditional \"ENABLE_SAMPLES\" was never defined.
+  { { echo "$as_me:4898: error: conditional \"ENABLE_SAMPLES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"ENABLE_SAMPLES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
@@ -4902,7 +4905,7 @@ fi
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:4905: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:4908: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -5033,7 +5036,7 @@ EOF
 
 cat >>$CONFIG_STATUS <<EOF
 ac_cs_version="\\
-soapcpp2 config.status 2.2.1
+soapcpp2 config.status 2.2.2
 configured by $0, generated by GNU Autoconf 2.52,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
@@ -5078,7 +5081,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:5081: error: ambiguous option: $1
+    { { echo "$as_me:5084: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -5097,7 +5100,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:5100: error: unrecognized option: $1
+  -*) { { echo "$as_me:5103: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -5116,7 +5119,7 @@ cat >&5 << _ACEOF
 ## Running config.status.  ##
 ## ----------------------- ##
 
-This file was extended by $as_me (soapcpp2 2.2.1) 2.52, executed with
+This file was extended by $as_me (soapcpp2 2.2.2) 2.52, executed with
   CONFIG_FILES    = $CONFIG_FILES
   CONFIG_HEADERS  = $CONFIG_HEADERS
   CONFIG_LINKS    = $CONFIG_LINKS
@@ -5168,7 +5171,7 @@ do
   "soapcpp2/samples/events/Makefile" ) CONFIG_FILES="$CONFIG_FILES soapcpp2/samples/events/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:5171: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:5174: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -5429,7 +5432,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:5432: creating $ac_file" >&5
+    { echo "$as_me:5435: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -5447,7 +5450,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5450: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5453: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5460,7 +5463,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5463: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5466: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5521,7 +5524,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:5524: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:5527: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -5532,7 +5535,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5535: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5538: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5545,7 +5548,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5548: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5551: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5662,7 +5665,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:5665: $ac_file is unchanged" >&5
+      { echo "$as_me:5668: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
